# Display escape characters
print("\n Displays a new line")
print("\t Displays a tab space")
print("\\ Displays a back slash")
print("\" Displays a double quote")
print("\' Displays a single quote\n")

print("\t \t hi \t \t hi")
print("\t \t hi \t \t hi")
print("\t \t hi \t \t hi")
print("\t \t hihihihihihihi")
print("\t \t hi \t \t hi")
print("\t \t hi \t \t hi")
print("\t \t hi \t \t hi")
print("\t \t hi  O \t O \t hi")
print("\t \t hi \t \t hi")
print("\t \t hi -------  hi")
print("\t \t hi \t \t hi")
print("\t \t hihihihihihihi")
print("\t \t  I am a beep")
